name: Publish Docker Images

on:
  push:
    branches:
      - main
jobs:
  publish-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build and Publish master
        uses: VaultVulp/gp-docker-action@master
        with:
          github-token: ${{ secrets.TOKEN }}
          image-name: gobuilder
          inage-tag: latest
